### ISSUE TITLE
Tables.jl integration

### ISSUE THREAD

**Issue by quinnj** [felipenoris/XLSX.jl#1]
This is a super exciting package! I've wanted a pure-Julia excel reader for a while. I'd be very interested in helping put together a DataStreams integration to hook into all the other data formats out there if you're open to a PR.

**Comment by felipenoris** [comment]
@quinnj, you're the one that got me into Julia in the first place with the SQLite stuff.
Yes, I would like to help on that!

**Comment by piever** [comment]
+1 on this one! It'd be really cool to be able to read an excel file as say a `NamedTuple` of vectors rather than `Array{Any}`.

**Comment by felipenoris** [comment]
@piever yes. #4 will pave the way for that.

**Comment by EricForgy** [comment]
Ok. Now that you have `gettable`, I guess it should be fairly straightforward to integrate with Tables.jl now, right? 😊 

I have no idea what is involved, but maybe I could take a crack at it? (surely I would mess it up though 😅)

**Comment by EricForgy** [comment]
I had a quick look at this and think it is not so simple. If I'm not mistaken, chunks of this package could be simplified if it were to use the Tables interface, so it may not be just a matter of implementing the interface from `gettable` (although that could be done).

**Comment by EricForgy** [comment]
Oh. It looks like there is some Tables integration already:

https://youtu.be/vfxS6_Sx1Pk?list=PLP8iPy9hna6SUVDR2Q_MQmP_f5cgcO7Vu&t=3818

https://github.com/felipenoris/XLSX.jl/blob/master/src/write.jl#L606

https://github.com/felipenoris/XLSX.jl/blob/master/test/runtests.jl#L1731-L1789

🤔 

That doesn't quite look like the Tables interface from the Tables docs though. Is that complete? Should this issue be closed?

**Comment by EricForgy** [comment]
Oh. @quinnj is on the case 👍 Should have popped me a note. Something like, "Hold my 🍺" 😄
