### ISSUE TITLE
Julia 0.6

### ISSUE THREAD

**Issue by cwiese** [felipenoris/XLSX.jl#102]
Is there a version (tag or branch) that I can clone that works with Julia 0.6?   We are migrating to Julia 1.0 - but not there yet.

**Comment by felipenoris** [comment]
If you use `Pkg.add("XLSX")` on Julia v0.6 you'll get Release v0.3.0 (https://github.com/felipenoris/XLSX.jl/releases/tag/v0.3.0).

It is still usable an version, but lacks a few minor bugfixes and new features.

**Comment by cwiese** [comment]
thanks for the quick reply ... I get this error after  `Pkg.add("XLSX")` 

WARNING: julia is fixed at 0.6.4 conflicting with requirement for TableView: [0.7.0,∞)
WARNING: julia is fixed at 0.6.4 conflicting with requirement for Homebrew: [0.7.0,∞)
ERROR: Tables can't be installed because it has no versions that support 0.6.4 of julia. You may need to update METADATA by running `Pkg.update()`

**Comment by felipenoris** [comment]
Your problem looks unrelated to the package XLSX.
I've just tested on a clean Julia v0.6 installation on Linux and macOS and it worked fine.

Maybe you have other packages installed that are incompatible with v0.6 ?

**Comment by cwiese** [comment]
Yeah - we have many pinned packaged - so that we do not get unexpected updates to our application.

**Comment by cwiese** [comment]
my other packages in a bad state thanks
