### ISSUE TITLE
can't open excel file with openpyxl. 

### ISSUE THREAD

**Issue by ericwathome** [felipenoris/XLSX.jl#105]
Am trying to create an instance where I send grouped messages to a group of numbers using python. Am getting the error below.

here is the code that gives me the error: 

#######################################
from ipaddress import IPv4Address
from pyairmore.request import AirmoreSession
from pyairmore.services.device import DeviceService
from pyairmore.services.messaging import MessagingService
from openpyxl import load_workbook

ip = IPv4Address("192.168.0.3")
session = AirmoreSession(ip)
service = DeviceService(session)
details = service.fetch_device_details()

service = MessagingService(session)

filepath = r"C:\Users\User\PycharmProjects\bulk\contacts.xlsx"

column = "A"
length = 3
workbook = load_workbook(filename="contacts.xlsx", read_only=True)
worksheet = wb.active
phone_numbers = []
for i in range(length):
 cell = "{}{}".format(column, i + 1)
 number = worksheet[cell].value
 if number != "" or number is not None:
  phone_numbers.append(str(number))
  message = "50% discount at Lorem Ipsum Co. tomorrow."
  for number in phone_numbers:
   service.send_message(number, message)
################################################

C:\Users\User\PycharmProjects\bulk\venv\Scripts\python.exe C:/Users/User/PycharmProjects/bulk/bulk.py
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/bulk/bulk.py", line 18, in <module>
    workbook = load_workbook(filename="contacts.xlsx", read_only=True)
  File "C:\Users\User\PycharmProjects\bulk\venv\lib\site-packages\openpyxl\reader\excel.py", line 311, in load_workbook
    data_only, keep_links)
  File "C:\Users\User\PycharmProjects\bulk\venv\lib\site-packages\openpyxl\reader\excel.py", line 126, in __init__
    self.archive = _validate_archive(fn)
  File "C:\Users\User\PycharmProjects\bulk\venv\lib\site-packages\openpyxl\reader\excel.py", line 98, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by felipenoris** [comment]
Maybe you opened this issue in the wrong github repo? This is XLSX.jl for the Julia language, not openpyxl for Python.

Looks like your Excel file is corrupted, since it is not a valid ZIP file.

**Comment by ericwathome** [comment]
Thanks for the response. Am new to programming, so sorry about the mistake. Now in terms of the zip file, I've just created it with python, I don't get why it's corrupted.

**Comment by felipenoris** [comment]
From your code, I woukd guess two things:

1) you may be passing the wrong file location. Try replacing `load_workbook(filename="contacts.xlsx", read_only=True)` by `load_workbook(filename=filepath, read_only=True)`, since you defined the `filepath` variable.

2) try opening contracts.xlsx with you Excel app to check if the file is corrupted.

**Comment by ericwathome** [comment]
Thanks for the help. It finally worked. Is there a way to bypass the
maximum limit when am for instance sending 1000 messages?

**Comment by LikhithaRamisetty** [comment]
How did it work? I'm getting same badzip file error with openpyxl. Kindly help
