### ISSUE TITLE
Writing tuples in Excel

### ISSUE THREAD

**Issue by Schepy** [felipenoris/XLSX.jl#107]
`a1=[(1,2) (3,4) (5,6)]`
`a2=[(1,2); (3,4); (5,6);]`

The following code writes exactly the same results regardless if a1 is used or a2.
Not having 3 named columns returns error.

`XLSX.openxlsx("test.xlsx", mode="w") do xf
    sheet = xf[1]
    XLSX.writetable!(sheet, a1,["n1","n2","n3"], anchor_cell=XLSX.CellRef("A1"))
end`

Excel file looks like:

n1| n2 | n3
1 | 3 | 5
2 | 4 | 6

I need tuples written in 2 columns which does not seem possible using this command.
Also, it would be nice not to be forced to name the columns.

Request a feature to write 2D arrays naturally without prior data transformation.

**Comment by felipenoris** [comment]
Please, refer to the docs on `writetable!`:

```
    writetable!(sheet::Worksheet, data, columnnames; anchor_cell::CellRef=CellRef("A1"))

Writes tabular data `data` with labels given by `columnnames` to `sheet`,
starting at `anchor_cell`.

`data` must be a vector of columns.
`columnnames` must be a vector of column labels.

See also: [`XLSX.writetable`](@ref).
```

This method expects `data` to be a vector. Each element of the vector is a column data.

I would suggest to write data directly to the Excel spreadsheet, instead of using the table API.

As in:

```julia
a2=[(1,2); (3,4); (5,6);]

XLSX.openxlsx("test.xlsx", mode="w") do xf
    sheet = xf[1]
    for row in 1:length(a2), col in 1:2
        sheet[row, col] = a2[row][col]
    end
end
```

which results in 

```
1 | 2
3 | 4
5 | 6
```
