### ISSUE TITLE
Repaired Records: Worksheet properties from /xl/workbook.xml part (Workbook)

### ISSUE THREAD

**Issue by cwiese** [felipenoris/XLSX.jl#108]
I created a workbook with 3 worksheet using writetable... when I open I get this "We found a problem with some content i..."

Any ideas?
[Revenue Variance.xlsx](https://github.com/felipenoris/XLSX.jl/files/3299492/Revenue.Variance.xlsx)

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Repair Result to Revenue Variance0.xml</logFileName><summary>Errors were detected in file '/Users/charleswiese/Documents/GitHub/nrbServer4/log/Revenue Variance.xlsx'</summary><repairedRecords summary="Following is a list of repairs:"><repairedRecord>Repaired Records: Worksheet properties from /xl/workbook.xml part (Workbook)</repairedRecord></repairedRecords></recoveryLog>

**Comment by felipenoris** [comment]
Can you provide the code that generates the excel file?

**Comment by cwiese** [comment]
getting the supporting data will be hard ... I did attached the xlsx also...thanks 

`file = "Revenue Variance"
    n = length(res_set.resultItems)
    n == 0 && error("stopping")
    dh_header = map(dhp->dhp.dimHier.dim.dimName, qry_req.drillByDimHier[1])
    msr_header = map(m->Definitions.get_msr(m.msr, scen).msrName, 
    res_set.resultItems[1].msrResults)
    header = vcat(dh_header, msr_header)

    xf = XLSX.open_xlsx_template(data_path*"/impact_template.xlsx")
    wb = XLSX.get_workbook(xf)
    sh = xf["data"]

    colsDH = [Vector{String}(n) for i in 1:length(dh_header)]
    colsMsr = [Vector{Float64}(n) for i in 1:length(msr_header)]
    for (row, ri) in enumerate(res_set.resultItems) #drill
        for (c, dha) in enumerate(ri.contextKeys)
            colsDH[c][row] = Definitions.attrval(dha)  #drill 1,2,3
        end
        for (m, msr) in enumerate(ri.msrResults)
            colsMsr[m][row] = msr.msrVal  #msr
        end
    end
    cols = vcat(colsDH,colsMsr)

    XLSX.writetable!(sh, cols, header; anchor_cell=XLSX.CellRef("A1"))

    for qprop in collect(values(scen_cube))
        for (drill, part_cube) in qprop.partition_results
            tabname = drill
            cols = [parse(Int64,x[2]) for x in sort([(value, key) for (key, value) in part_cube.cube_map["cols"]])]
            dh_header = map(x->Definitions.get_DH(x, scen).dim.dimName, cols)
            msr_header = [x[2] for x in sort([(value, key) for (key,value) in part_cube.cube_map["msrs"]])]
            header = vcat(dh_header, msr_header)
            msrs = map(m->Definitions.get_msr(m), msr_header)
            dat = collect(rows(part_cube.cube))
            n = length(dat)
            colsDH = [Vector{String}(n) for i in 1:length(dh_header)]
            colsMsr = [Vector{Float64}(n) for i in 1:length(msr_header)]
            offset = length(dh_header)
            for i = 1:n
                for (c, dh) in enumerate(cols)
                    colsDH[c][i] = row[c]>0 ? Definitions.attrval(row[c]) : ""
                end
                for (m, msr) in enumerate(msrs)
                    colsMsr[m][i] = row[m+offset]
                end
            end
            cols = vcat(colsDH,colsMsr)
            println("tabname $tabname n: $(n)")
            sh = XLSX.addsheet!(wb, tabname)
            XLSX.writetable!(sh, cols, header; anchor_cell=XLSX.CellRef("A1"))
        end
    end


    XLSX.writexlsx(log_path*"/$(file).xlsx", xf; overwrite=true)
`

**Comment by cwiese** [comment]
also ...

I am writing table with columns of data .. each column can have a different style.   How do I set the whole column ?
I see that you can crate a style 
`
numfmt = XLSX.styles_add_numFmt(wb, "\$* #,##0.00;\$* (#,##0.00);\$* \"-\"??;[Magenta]@")
`
and then set style and value:
`
setdata!(sheet, CellRef("A2"), CellValue(1000, numstyle))
`
or just a cell 
`
cell = getcell(sheet, "A6")
cell.style == id(numstyle)`

but I am using write table and need to set the whole column ??

**Comment by cwiese** [comment]
maybe this is because I am trying to update a preexisting template

**Comment by cwiese** [comment]
it seems the app.xml is missing that added worksheets,..... I will try a different approach 

Before excel repaired

``<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>Microsoft Macintosh Excel</Application><DocSecurity>0</DocSecurity><ScaleCrop>false</ScaleCrop><HeadingPairs><vt:vector size="2" baseType="variant"><vt:variant><vt:lpstr>Worksheets</vt:lpstr></vt:variant><vt:variant><vt:i4>1</vt:i4></vt:variant></vt:vector></HeadingPairs><TitlesOfParts><vt:vector size="1" baseType="lpstr"><vt:lpstr>data</vt:lpstr></vt:vector></TitlesOfParts><Company/><LinksUpToDate>false</LinksUpToDate><SharedDoc>false</SharedDoc><HyperlinksChanged>false</HyperlinksChanged><AppVersion>16.0300</AppVersion></Properties>``

repaired:

``<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>Microsoft Macintosh Excel</Application><DocSecurity>0</DocSecurity><ScaleCrop>false</ScaleCrop><HeadingPairs><vt:vector size="2" baseType="variant"><vt:variant><vt:lpstr>Worksheets</vt:lpstr></vt:variant><vt:variant><vt:i4>4</vt:i4></vt:variant></vt:vector></HeadingPairs><TitlesOfParts><vt:vector size="4" baseType="lpstr"><vt:lpstr>data</vt:lpstr><vt:lpstr>1_(40)</vt:lpstr><vt:lpstr>1_(12,40)</vt:lpstr><vt:lpstr>1_final</vt:lpstr></vt:vector></TitlesOfParts><Company></Company><LinksUpToDate>false</LinksUpToDate><SharedDoc>false</SharedDoc><HyperlinksChanged>false</HyperlinksChanged><AppVersion>16.0300</AppVersion></Properties>``

**Comment by cwiese** [comment]
solved:  even though I used XLSX.xlsx_escape(sheetname) and the worksheets do get added.... the use of square brackets in sheet names caused this issue .

**Comment by felipenoris** [comment]
@cwiese good to know you figured it out!
Sheetnames validation was implemented in https://github.com/felipenoris/XLSX.jl/issues/91. I'll check if something can be done to prevent this bug in the future.

**Comment by cwiese** [comment]
Thank you for your help ...I have  question on versions.   We are still on Julia 0.6 ..I see I am using  - XLSX 0.3.0

I get this issue ...  sheet[r, c] = blah... 
ERROR: LoadError: MethodError: no method matching getindex(::XLSX.Worksheet, ::Int, ::Int)

Can I pin a newer version?

**Comment by felipenoris** [comment]
@cwiese oh, I see. Maybe that's why you're getting this bug. The last version to support Julia v0.6 was XLSX v0.3.0 . All the new features and bug fixes are for Julia v0.7 and superior only.

**Comment by cwiese** [comment]
Okay .. dang I liked accessing by row index and column ... sheet[r, c] 

Maybe I will steal that function until we upgrade.

**Comment by felipenoris** [comment]
I just checked that bc541758a7bb964aa75d24f603d9e12f3cd4b132 does prevent `[` and `]` characters on sheetnames.
