### ISSUE TITLE
AssertionError: Malformed: couldn't find workbookPr node element in 'xl/workbook.xml'

### ISSUE THREAD

**Issue by cmcaine** [felipenoris/XLSX.jl#121]
```
julia> XLSX.readxlsx(fname)                                                                                                             
ERROR: AssertionError: Malformed: couldn't find workbookPr node element in 'xl/workbook.xml'
```

ExcelReaders.jl is able to read the file.

I'm not able to share the file because it contains confidential information and resaving a smaller example does not reproduce the issue. Possibly the file is slightly malformed and libreoffice is fixing that?

Edit: Resaving the whole file takes ages in libreoffice, but does produce a file that XLSX can read.

The file contains three sheets. Sheets have parentheses in their names. Each sheet contains ~50k rows.

**Comment by felipenoris** [comment]
Oh, this is an easy one.

**Comment by felipenoris** [comment]
@cmcaine , please check if the XLSX.jl version on the *master* branch fixes your problem.

**Comment by cmcaine** [comment]
readxlsx now loads the sheet, but it takes literally minutes to do so.

When it does load, I can't access the data of most cells because they are "inlineStr". I've made a new issue for that, #123

**Comment by cmcaine** [comment]
Thanks very much for the rapid fix!
