### ISSUE TITLE
openxlsx() not working with excel 2019?

### ISSUE THREAD

**Issue by uwbanjoman** [felipenoris/XLSX.jl#128]
I tried your example to create a new excel file, but all i get is a 3x3 Array{Int64,2} in the repl.
I'm using Julia 1.3.1 on windows 10 and my excel version is from office 2019

XLSX.openxlsx("my_new_file.xlsx", mode="w") do xf
       sheet = xf[1]
       XLSX.rename!(sheet, "new_sheet")
       sheet["A1"] = "this"
       sheet["A2"] = "is a"
       sheet["A3"] = "new file"
       sheet["A4"] = 100
       sheet["A5"] = collect(1:5) # equivalent to `sheet["A5", dim=2] = collect(1:4)
       sheet["B1", dim=1] = collect(1:4)
       sheet["A7:C9"] = [ 1 2 3 ; 4 5 6 ; 7 8 9 ]
       end

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

**Comment by felipenoris** [comment]
This is most likely not a problem. Please, check what is your current directory with `pwd()`.
In the following example the file is created in the folder `D:\Users\FNORO'.

![image](https://user-images.githubusercontent.com/12482900/80405947-b10cc780-8899-11ea-96d4-c94ffd47380b.png)
