### ISSUE TITLE
writetable without headers

### ISSUE THREAD

**Issue by cojua8** [felipenoris/XLSX.jl#133]
Hello,

I think columnames in `writetable!` should be optional:

If you have a complex header layout like the one in the image, you just want to get the data into the table and keep the headers just as they are

![image](https://user-images.githubusercontent.com/34746495/80401087-c548c880-8889-11ea-964b-f9e5565a60f1.png)

**Comment by felipenoris** [comment]
Hi! you can use `sheet["A4"] = m` , where `A4` is a cell anchor (could also be the cell range), and `m` is a julia matrix (`Array{T, 2}`) .

**Comment by cojua8** [comment]
yes!, I forgot I to say I was using a DataFrame, but I guess it's easier using `sheet["A4"] = Matrix(df)`
