### ISSUE TITLE
ZipFile performance

### ISSUE THREAD

**Issue by chris-b1** [felipenoris/XLSX.jl#135]
In doing some benchmarking on XLSX, ZipFile is huge bottleneck.  I started hacking around, and got about a 6-7x speedup in `XLSX.readtable` with this change - 

https://github.com/felipenoris/XLSX.jl/compare/master...chris-b1:zip-workarouund?expand=1

There are still some bugs and maybe should be pushed upstream to ZipFile, but I wanted to leave a note here in case I don't get back to it for a while.

**Comment by felipenoris** [comment]
@chris-b1 good work! Yes, I suspect many issues in this repo are related to the zip lib backend.

**Comment by chris-b1** [comment]
Added a PR to ZipFile that I think picks up the easy win with no changes needed here, but will leave this open as a tracker for now
https://github.com/fhs/ZipFile.jl/pull/68

**Comment by chris-b1** [comment]
Fixed by https://github.com/fhs/ZipFile.jl/pull/68 and released in ZipFile `0.9.2`
