### ISSUE TITLE
Cannot index multiletter column name (e.g `sheetname["AA"]`)

### ISSUE THREAD

**Issue by kdheepak** [felipenoris/XLSX.jl#138]
This line checks for `length`. It should instead check if `:` is in the string. 

https://github.com/felipenoris/XLSX.jl/blob/2dbe3ade2c4481eb8543e796d70e8a20fa81a681/src/cellref.jl#L273

**Comment by felipenoris** [comment]
Thanks for finding this!!!!

**Comment by felipenoris** [comment]
Fixed by 5c323389ab990d5c7cb322569cfb2c271c3f403e.
