### ISSUE TITLE
I cannot read XLS files with this package. Any ideas how I can read XLS files?

### ISSUE THREAD

**Issue by manuzrp** [felipenoris/XLSX.jl#142]
I cannot read XLS files with this package. Any ideas how I can read XLS files? I appreciate it.

**Comment by felipenoris** [comment]
Please, refer to https://github.com/queryverse/ExcelReaders.jl.

**Comment by manuzrp** [comment]
But ExcelReaders doesn't read .xls files, does it? How can I read a .xls files in Julia (from a URL)?

**Comment by felipenoris** [comment]
It does read XLS.

**Comment by manuzrp** [comment]
Can you prove it with an example? I haven't found any example.

**Comment by felipenoris** [comment]
@manuzrp you can try yourself. Just follow the [Basic Usage](https://github.com/queryverse/ExcelReaders.jl#basic-usage) examples.

**Comment by manuzrp** [comment]
You are right. It indeed reads a local .xls file (readxlsheet command). Thank you.
