### ISSUE TITLE
How to use XLSX.readtable to read a worksheet range

### ISSUE THREAD

**Issue by sbacelar** [felipenoris/XLSX.jl#144]
I understood from reading the API that `XLSX.readtable` has not a `stop_in_row` = x parameter.
My problem is: I want to read several worksheets from the same workbook using always the range A2:P32. I don't know how to define P32.

I want to import the results to a DataFrame.

**Comment by felipenoris** [comment]
@sbacelar, maybe there's a way to do it with `readtable` if you use the more advanced options of the API, as documented at https://felipenoris.github.io/XLSX.jl/stable/api/#XLSX.readtable.

You can also use `XLSX.readdata("myfile.xlsx", "mysheet", "A2:P32")` and get the data as a matrix. Then you'll have to convert it to a DataFrame yourself.
