### ISSUE TITLE
Support writing of integer types smaller than Int64

### ISSUE THREAD

**Issue by kobusherbst** [felipenoris/XLSX.jl#166]
Is it possible to support integer types smaller than Int64, e.g. Int8, Int16 and Int32 directly for writing to sheets, preventing this error: `Unsupported datatype Int8 for writing data to Excel file.`

**Comment by felipenoris** [comment]
Similar to #167 , if I store a Int8 inside Excel, when I read it back I can't tell that it was Int8. So I guess you should cast to In64 before storing the value.

**Comment by kobusherbst** [comment]
I don't mind reading it back as an Int64, casting many fields to Int64 is cumbersome and not consistent with Julia's automatic type casting rules.

**Comment by felipenoris** [comment]
@kobusherbst you have a good point.

[These](https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#When-is-convert-called?) are the current rules for automatic casting:

* Assigning to an array converts to the array's element type.

* Assigning to a field of an object converts to the declared type of the field.

* Constructing an object with new converts to the object's declared field types.

* Assigning to a variable with a declared type (e.g. local x::T) converts to that type.

* A function with a declared return type converts its return value to that type.

* Passing a value to ccall converts it to the corresponding argument type.

With which of these rules do you understand that XLSX.jl is not consistent with?

**Comment by kobusherbst** [comment]
`julia> a = Int64(10)`
10
`julia> b = Int8(1)`
1
`julia> c = a + b`
11
`julia> typeof(c)`
Int64
`julia> d = b + a`
11
`julia> typeof(d)`
Int64

**Comment by felipenoris** [comment]
@kobusherbst I guess these convertions are mentioned in [Automatic promotion for built-in arithmetic types and operators](https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#conversion-and-promotion), which apply to math operations and I guess this is not the case here.

However, by the first rule `Assigning to an array converts to the array's element type` we have:

```julia
julia> v = Vector{Int}()
Int64[]

julia> push!(v, UInt8(200))
1-element Array{Int64,1}:
 200

julia> typeof(v[1])
Int64

julia> v[1] = UInt8(100)
0x64

julia> typeof(v[1])
Int64
```

It is not mentioned in the docs, but it also applies to containers like a `Dict`:

```julia
julia> x = Dict{String, Int}()
Dict{String,Int64}()

julia> x["a"] = Int8(1)
1

julia> typeof(ans)
Int8

julia> typeof(x["a"])
Int64
```

All these goes in favor of your proposal. So I would say it is fair to implement it.

**Comment by felipenoris** [comment]
Superseded by #191.
