### ISSUE TITLE
Unsupported datatype DecFP.Dec128 for writing to Excel

### ISSUE THREAD

**Issue by metanoid** [felipenoris/XLSX.jl#167]
Some data operations may result in data stored in a DecFP format.
It would be nice if this data could be written to Excel, but currently DecFP.Dec128 is not in the list of supported data types.
Supported data types are Union{Missing, Bool, Float64, Int64, Date, DateTime, Time, String} or XLSX.CellValue.

**Comment by felipenoris** [comment]
Excel uses Float64 internally to represent numbers, AFAIK. So you should cast to a Float64 before storing Dec128 inside Excel.
I'll close this for now. Please, feel free to reopen if you find a reference showing that Excel does support Dec128.
