### ISSUE TITLE
Unsupported datatypes converted to strings

### ISSUE THREAD

**Issue by hdavid16** [felipenoris/XLSX.jl#171]
It would be helpful if any unsupported datatypes (e.g., `Tuple`, `Symbol`) were internally converted to `String` (the behavior of CSV.jl). This would make writing more user-friendly (not having to go through each table to convert data to strings, which can be cumbersome especially when writing an Excel workbook with many sheets from many tables).

**Comment by felipenoris** [comment]
Superseded by #191.
