### ISSUE TITLE
Rename duplicated column names when reading excel file

### ISSUE THREAD

**Issue by ulinares** [felipenoris/XLSX.jl#174]
Hi everyone,

Just wondering why to throw an `AssertionError` if a table has repeated column names when reading it with `XLSX.readtable`, would not be convenient just to append an index to the name of every repeated column instead of throwing the error?

**Comment by hdavid16** [comment]
Agreed.

Another thing that would be helpful would be to pass a vector of columns to read. This currently throws a MethodError since the `readtable` function is expecting a string for the `columns` argument.

**Comment by felipenoris** [comment]
Fixed in #164
