### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by yuanhu7069** [felipenoris/XLSX.jl#197]
我测试了一下读取CSV文件写入Excel，并且和pyhton pandas做了对比，70万行17列的数据量，xlsx.jl的速度比python pandas速度慢1/3，试图找到快速的方法，未果。

df = CSV.read(path, DataFrame,types=String)
 data = collect(eachcol(df))
    cols = names(df)
    XLSX.writetable(path, data, cols)

**Comment by felipenoris** [comment]
@ivan-lee-16 你是完全正确的。.

Closing as a dup of #61.
