### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by rjplevin** [felipenoris/XLSX.jl#20]
Hi, Felipe. Thanks for the quick fix!

Next issue: when I replace ExcelReaders with XLSX, the time to setup my model increases from 0.6 sec to 5 sec. I was hoping to get rid of the Python dependencies with a pure Julia reader, but the performance is prohibitive. Any thoughts on improving performance?

**Comment by felipenoris** [comment]
@rjplevin In my benchmarks XLSX.jl is between 2x to 4x faster than ExcelReaders.
Can you give me some detail on what are you doing and what is taking more time to complete?
Is it with the same excel file?

**Comment by rjplevin** [comment]
Yes, it's loading the same file I sent you earlier. The code simply reads the workbook and grabs data from a few dozen locations in one or two sheets.

Here are timing results using ExcelReaders:
```
Main> @time begin dice2010_excel_parameters(datafile, useXLSX=false); nothing end
  0.596591 seconds (48.39 k allocations: 1.662 MiB)
```
And XLSX:
```
Main> @time begin dice2010_excel_parameters(datafile, useXLSX=true); nothing end
  4.981956 seconds (29.61 M allocations: 910.835 MiB, 3.18% gc time)
```
These were both after prior "warm up" runs.

Given the differences in # allocations and mem usage, I'm guessing that ExcelReaders processes worksheets lazily, so it's ignoring the bulk of the workbook. It looks like XLSX processes the entire workbook in `XLSX.read()`. Maybe implement separate `open(workbook)` and `read(worksheet)` functions?

**Comment by felipenoris** [comment]
Yes, the entire workbook is read so that you don´t need to access the file afterwards. There´s one idea in #3 to improve that, but it will take some time.

Can you post the implementation of your functions with the data access parts?

**Comment by rjplevin** [comment]
Here's the file. You just need to point `datafile` to the file I sent previously.

[parameters.jl.zip](https://github.com/felipenoris/XLSX.jl/files/1992288/parameters.jl.zip)

**Comment by felipenoris** [comment]
Yes, it's a good opportunity to implement lazy loading of XML files. I'll work on that.

**Comment by rjplevin** [comment]
Thanks for being so responsive!

**Comment by felipenoris** [comment]
Done! Thank you!
