### ISSUE TITLE
Make written cell types less restrictive

### ISSUE THREAD

**Issue by bkamins** [felipenoris/XLSX.jl#201]
Currently the list in https://github.com/felipenoris/XLSX.jl/blob/d2f51a80fcf24b4887aeb61dae8637baef80e3d8/src/types.jl#L59 is restrictive. See for example https://stackoverflow.com/questions/72955139/error-when-going-from-dataframe-to-excel-file-in-julia where an issue related to it is reported. Maybe it could be considered to accept more general abstract types instead of concrete types and perform appropriate conversions when writing data (e.g. instead of `String` accept `AbstractString`)

**Comment by felipenoris** [comment]
@bkamins thanks for the input!
Closing as a dup of #191.

**Comment by bkamins** [comment]
I have looked at #191 but I was not sure it was exactly the same thing.
