### ISSUE TITLE
XLSX.jl on Julia 1.8

### ISSUE THREAD

**Issue by deel-sider** [felipenoris/XLSX.jl#209]
Hi,

This is what I get when I run a script that worked well on 1.7.3 with 1.8:

ERROR: LoadError: MethodError: no method matching iterate(::XLSX.DataTable)
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at range.jl:872
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at range.jl:872
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at dict.jl:712
  ...
Stacktrace:
 [1] top-level scope

This was triggered by calling the readable function in a manner like the following: 

df = DataFrame(XLSX.readtable(<file path>, <worksheet path>)...)

Admittedly, Julia 1.8 is very new but I thought it best to let you know. For now, I am sticking with the older version.

**Comment by Boxylmer** [comment]
Did you accidentally upgrade XLSX when you moved Julia versions? There's a breaking change that modified the output of getting tables

https://felipenoris.github.io/XLSX.jl/stable/migration/#Migrating-Legacy-Code-to-v0.8

**Comment by deel-sider** [comment]
Yes, moving Julia version did cause the reinstallation of some packages so an upgrade may have happened. Removing the splat character as documented in the link did the job for me so everything is working now.

Many thanks for a very useful package and for the advice,

John

**Comment by Boxylmer** [comment]
Haha, no problem, but you have @felipenoris to thank, not me! I just ran into the same issue the day before because I was sloppy with my manifest!
