### ISSUE TITLE
gettable doesn't support arguments shown in documentation

### ISSUE THREAD

**Issue by jomavera** [felipenoris/XLSX.jl#230]
`XLSX.gettable` doesn't allow `columns` argument. 
Tested `gettable(::XLSX.Worksheet; columns="B:C", first_row=9, header=true)` and raises MethodError, closest candidate suggested `gettable(::XLSX.Worksheet; first_row, column_labels, header, infer_eltypes, stop_in_empty_row, stop_in_row_function)`

**Comment by felipenoris** [comment]
`columns` is not a kwarg.
Please, try `gettable(::XLSX.Worksheet, "B:C", first_row=9, header=true)`.
