### ISSUE TITLE
readtable returns a float when piped through DataFrame

### ISSUE THREAD

**Issue by gyansinha** [felipenoris/XLSX.jl#231]
I can't quite explain what's going on here?

df = XLSX.readtable(fname, "Worksheet") |> DataFrame
0.051024000000025715

df contains a float instead of returning the dataframe!

[ventr_2019_36a_20230614.xlsx](https://github.com/felipenoris/XLSX.jl/files/11749591/ventr_2019_36a_20230614.xlsx)

**Comment by felipenoris** [comment]
Hi! I couldn't reproduce this.

![image](https://github.com/felipenoris/XLSX.jl/assets/12482900/23d09575-0d68-4bd6-8809-c74824fbdd61)

**Comment by gyansinha** [comment]
I'll be damned! i must have corrupted my julia session somehow - or clobbered something in the DataFrame namespace by mistake. Thank your testing this. It works as it should with a fresh session.
