### ISSUE TITLE
Cannot convert XLSX table into a Dataframe

### ISSUE THREAD

**Issue by MorsePotential** [felipenoris/XLSX.jl#236]
Hi all,

Julia version: 1.9.2

Unsure what went wrong for me but I am a bit puzzled. I am trying to convert an xlsx table (file attached) into a Dataframe. When I run my test.jl in repl using the code below, it throws the following error:

My code:
```
using XLSX,DataFrames

data=XLSX.readtable("./testfiles/exceltest1.xlsx","test1",;header=true)

df=DataFrame(data)

```

Error:
`ERROR: LoadError: ArgumentError: 'Tuple{Vector{Any}, Vector{Symbol}}' iterates 'Vector{Any}' values, which doesn't satisfy the Tables.jl `AbstractRow` interface
Stacktrace:
 [1] invalidtable(#unused#::Tuple{Vector{Any}, Vector{Symbol}}, #unused#::Vector{Any})
   @ Tables ~/.julia/packages/Tables/AcRIE/src/tofromdatavalues.jl:41
 [2] iterate
   @ ~/.julia/packages/Tables/AcRIE/src/tofromdatavalues.jl:47 [inlined]
 [3] buildcolumns
   @ ~/.julia/packages/Tables/AcRIE/src/fallbacks.jl:209 [inlined]
 [4] _columns
   @ ~/.julia/packages/Tables/AcRIE/src/fallbacks.jl:274 [inlined]
 [5] columns
   @ ~/.julia/packages/Tables/AcRIE/src/fallbacks.jl:258 [inlined]
 [6] DataFrame(x::Tuple{Vector{Any}, Vector{Symbol}}; copycols::Nothing)
   @ DataFrames ~/.julia/packages/DataFrames/58MUJ/src/other/tables.jl:57
 [7] DataFrame(x::Tuple{Vector{Any}, Vector{Symbol}})
   @ DataFrames ~/.julia/packages/DataFrames/58MUJ/src/other/tables.jl:48
 [8] top-level scope
   @ ~/Desktop/My repos/hyperpure/test.jl:124`

However, when I run it in a Pluto notebook it works just fine ( screenshot below):

<img width="713" alt="image" src="https://github.com/felipenoris/XLSX.jl/assets/9093304/0f726dfd-8ff3-41cf-8c74-d478af28e008">

Also if I use CSV module rather than XLSX everything works fine, hence me asking here. Screenshot attached:

<img width="896" alt="image" src="https://github.com/felipenoris/XLSX.jl/assets/9093304/371c36ac-696d-4fbf-9e5f-2555d4b0f84f">

I am a bit stumped.

[exceltest1.xlsx](https://github.com/felipenoris/XLSX.jl/files/12313466/exceltest1.xlsx)

**Comment by korilium** [comment]
what is your version of XLSX? Maybe you have an older version of XLSX. 

try the following: 

`using Pkg
Pkg.update("XLSX")`

**Comment by MorsePotential** [comment]
The version of the XLSX is the following

```
⌅ [fdbf4ff8] XLSX v0.7.10
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated`
```

And no changes post update:
```

julia> Pkg.update("XLSX")
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.9/Project.toml`
  No Changes to `~/.julia/environments/v1.9/Manifest.toml`
```

**Comment by MorsePotential** [comment]
I have removed a module called https://github.com/queryverse/ExcelFiles.jl which kept the XLSX version to 0.7.10 for compatibility. Afterwards updated XLSX to 0.9 and now everything works. Thanks @korilium for helping me troubleshoot this.
