### ISSUE TITLE
How to cite this package?

### ISSUE THREAD

**Issue by juliohm** [felipenoris/XLSX.jl#242]
Hi @felipenoris ! Hope you are doing well!

Can you please share a bibtex entry for citation? :)

**Comment by juliohm** [comment]
@felipenoris mind adding a Zenodo entry for the package?

**Comment by TimG1964** [comment]
Hi @juliohm. Did you close this because it is no longer desirable? I couldn't find a Zenodo entry.

**Comment by juliohm** [comment]
I closed because I didn't get a response. It would be great to have a
zenodo entry for the package.

Em qua., 29 de abr. de 2026, 07:20, TimG1964 ***@***.***>
escreveu:

**Comment by TimG1964** [comment]
I don't know Zenodo but Copilot says doing this would be easy. I'll look into it and update here one way or the other.

**Comment by TimG1964** [comment]
https://zenodo.org/records/19894703
