### ISSUE TITLE
XML streaming to handle large Excel files

### ISSUE THREAD

**Issue by felipenoris** [felipenoris/XLSX.jl#3]
One drawback of the current implementation for this package is that the whole XML file from a ~Excel package are parsed in the moment the file is read at `XML.read("filename.xlsx")`~ worksheet is parsed when accessing any information of the worksheet.

One idea is to stream XML for worksheet XML files.

I found that [EzXML.jl](https://github.com/bicycle1885/EzXML.jl) has support for streaming XML files.

**Comment by stugorf** [comment]
@felipenoris I want to read an Excel file from an AWS S3 bucket without downloading it. It looks like this feature of ExcelFiles should work. This is how I normally read a file from a stream. Can you clarify how to read a stream using the XML Streaming feature:

file_content = S3.get_object(aws, get_config);
load(file_content, "Sheet1") |> DataFrame

Thank you.

**Comment by felipenoris** [comment]
Hi! For not it is not possible to read an excel file from stream. We would need https://github.com/felipenoris/XLSX.jl/issues/26 to be implemented.

**Comment by stugorf** [comment]
Thank you. Do you know of any packages that can read from stream currently?

**Comment by felipenoris** [comment]
I think there isn't. But I'll try to work on #26 though.

**Comment by stugorf** [comment]
If I can test anything, please do not hesitate to let me know!

Regards,

--David
