### ISSUE TITLE
encoding problem - exporting values with  `&` char

### ISSUE THREAD

**Issue by ImreSamu** [felipenoris/XLSX.jl#40]
Hi!
First, thank you for this package! 

I have found a strange encoding problem: - with exporting values with `&` character   - can you replicate ?

### minimal code:

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.4 (2018-07-09 19:09 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> import DataFrames, XLSX

julia> Pkg.status("XLSX")
 - XLSX                          0.2.2

julia> df1 = DataFrames.DataFrame(COL1=[10,20,30], COL2=["Fist%1row", "Sec&2row", "Third#3row"])
3×2 DataFrames.DataFrame
│ Row │ COL1 │ COL2       │
├─────┼──────┼────────────┤
│ 1   │ 10   │ Fist%1row  │
│ 2   │ 20   │ Sec&2row   │
│ 3   │ 30   │ Third#3row │

julia> XLSX.writetable("df1.xlsx", DataFrames.columns(df1), DataFrames.names(df1))

```

### Result - with LibreOffice Calc

"`Sec&2row`" value is missing:

![screenshot from 2018-07-18 18-39-51](https://user-images.githubusercontent.com/2217320/42895393-154d834a-8aba-11e8-8eae-344b36e1ba16.png)

### Expecting:

```
│ COL1 │ COL2       │
┼──────┼────────────┤
│ 10   │ Fist%1row  │
│ 20   │ Sec&2row   │  <---------
│ 30   │ Third#3row │  <---------
```

**Comment by ImreSamu** [comment]
I have added a minimal test  ( #53  )  for testing escaping 

According to my best knowledge - everything is OK :)

**Comment by felipenoris** [comment]
If you export data with those special characters and import it back (using writetable, readtable), do you get the same data?

**Comment by ImreSamu** [comment]
Honestly - My expectation was : that I have fixed only the "write" part ...  
And I need to create a "read" patch ... 

but now  - I have realized -   it is working, no bug.    My expectation was bad. 
I don't understand,    :confused:  ,  why?

Thanks again for this package :+1:

**Comment by felipenoris** [comment]
I´ll take a look at it again. I wrote a test on this a few weeks ago and it wasn´t working. But at least it works for the tests you wrote. Thanks for your contributions!

**Comment by ImreSamu** [comment]
> Maybe the contributions from other people fixed this.

You are right! 

Ouch ...
my fix - not was perfect ...   and the other gentleman contributor fixed :) https://github.com/felipenoris/XLSX.jl/commit/fe7fbe6f2a9120182df63e4ca054490252b958ef

Thanks @morris25 !
