### ISSUE TITLE
XLSX.jl locks file on Windows / Julia 0.7

### ISSUE THREAD

**Issue by zundertj** [felipenoris/XLSX.jl#42]
While attempting to make this package run on Julia 0.7-beta2, I ran into this (I cannot reproduce this on Julia 0.6.2!)

I'm on a Windows 10 machine, and this error keeps popping up while running the tests on the very last line where `rm("output_tables.xlsx")` is called:

```
ERROR: LoadError: unlink: resource busy or locked (EBUSY)
Stacktrace:
 [1] uv_error at .\libuv.jl:80 [inlined]
 [2] unlink(::String) at .\file.jl:741
 [3] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:253
 [4] rm(::String) at .\file.jl:245
 [5] top-level scope at none:0
 [6] include at .\boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1034
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] include(::String) at .\client.jl:393
 [10] top-level scope at none:0
in expression starting at C:\Users\Gebruiker\.julia\dev\XLSX\test\runtests.jl:1035
ERROR: Package XLSX errored during testing
```
Apparantly, this is a common problem on Windows with respect to file IO, see for instance [https://discourse.julialang.org/t/windows-specific-uv-error/3127/8](url).

I suspect that it might (partially) be a base Julia bug, but for some reason it only fails at the last  `rm("output_tables.xlsx")`, and not on previous calls. Do you have any idea what is so special about this last time, are there operations in the final set of tests that make it lock the file?

**Comment by zundertj** [comment]
Nevermind, I'm now also running into this on earlier calls to `rm()` in the test suite... Still, good for you to know that on Windows+Julia 0.7 tests are likely to fail because of this.

**Comment by felipenoris** [comment]
I don't know how to fix this.

**Comment by zundertj** [comment]
The question is: can you, or someone else, reproduce this (in Julia 0.7/1.0)?

**Comment by felipenoris** [comment]
Yes... travis build reproduced this problem. I tried to fix it by ensuring deallocation of variables that could be locking the file. But it didn't work. Maybe I'm leaving some stream opened after calling `close` method, but I can't find the problem.

**Comment by felipenoris** [comment]
https://ci.appveyor.com/project/felipenoris/xlsx-jl/build/1.0.3/job/esc8f8vk5vvoc5g8
