### ISSUE TITLE
Julia 0.7 Win7/ 64 error

### ISSUE THREAD

**Issue by programistawpf** [felipenoris/XLSX.jl#49]
D:\pawel\Julia_7.0_otwarty>C:\Users\PC\AppData\Local\Julia-0.7.0\bin\julia.exe -L start.jl

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

(v0.7) pkg> up
  Updating registry at `C:\Users\PC\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\PC\.julia\environments\v0.7\Project.toml`
 [no changes]
  Updating `C:\Users\PC\.julia\environments\v0.7\Manifest.toml`
 [no changes]

(v0.7) pkg> add XLSX
 Resolving package versions...
 Installed ZipFile ─ v0.6.0
 Installed EzXML ─── v0.8.0
 Installed XLSX ──── v0.2.2
  Updating `C:\Users\PC\.julia\environments\v0.7\Project.toml`
  [fdbf4ff8] + XLSX v0.2.2
  Updating `C:\Users\PC\.julia\environments\v0.7\Manifest.toml`
  [8f5d6c58] + EzXML v0.8.0
  [fdbf4ff8] + XLSX v0.2.2
  [a5390f91] + ZipFile v0.6.0
  Building EzXML → `C:\Users\PC\.julia\packages\EzXML\3U9Ow\deps\build.log`

(v0.7) pkg> up
  Updating registry at `C:\Users\PC\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\PC\.julia\environments\v0.7\Project.toml`
 [no changes]
  Updating `C:\Users\PC\.julia\environments\v0.7\Manifest.toml`
 [no changes]

julia> using XLSX
[ Info: Precompiling XLSX [fdbf4ff8-1666-58a4-91e7-1b58723a45e0]
┌ Warning: `method_exists(f, t)` is deprecated, use `hasmethod(f, t)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
WARNING: importing deprecated binding Base.Dates into XLSX.
WARNING: Base.Dates is deprecated, run `using Dates` instead
  likely near C:\Users\PC\.julia\packages\XLSX\ETIGH\src\structs.jl:45
WARNING: Base.Dates is deprecated, run `using Dates` instead
  likely near C:\Users\PC\.julia\packages\XLSX\ETIGH\src\structs.jl:45
WARNING: Base.Dates is deprecated, run `using Dates` instead
  likely near C:\Users\PC\.julia\packages\XLSX\ETIGH\src\structs.jl:45
WARNING: importing deprecated binding Base.Nullable into XLSX.
ERROR: LoadError: LoadError: TypeError: in Type{...} expression, expected UnionAll, got typeof(Base.Nullable)
Stacktrace:
 [1] top-level scope at none:0
 [2] include at .\boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1038
 [4] include at .\sysimg.jl:29 [inlined]
 [5] include(::String) at C:\Users\PC\.julia\packages\XLSX\ETIGH\src\XLSX.jl:3
 [6] top-level scope at none:0
 [7] include at .\boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at .\loading.jl:1038
 [9] include(::Module, ::String) at .\sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at .\boot.jl:319 [inlined]
 [12] eval(::Expr) at .\client.jl:399
 [13] top-level scope at .\none:3
in expression starting at C:\Users\PC\.julia\packages\XLSX\ETIGH\src\structs.jl:153
in expression starting at C:\Users\PC\.julia\packages\XLSX\ETIGH\src\XLSX.jl:14
ERROR: Failed to precompile XLSX [fdbf4ff8-1666-58a4-91e7-1b58723a45e0] to C:\Users\PC\.julia\compiled\v0.7\XLSX
\gPxqz.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] macro expansion at .\logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1185
 [4] _require(::Base.PkgId) at .\logging.jl:311
 [5] require(::Base.PkgId) at .\loading.jl:852
 [6] macro expansion at .\logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at .\loading.jl:834

julia>

Paul

**Comment by felipenoris** [comment]
This package does not support v0.7 yet.
You can check a WIP version on branch XLSX#v0.7

**Comment by programistawpf** [comment]
I am waiting .
What is "WIP version" ?
Paul
W dniu 2018-08-12 o 16:08, Felipe Noronha pisze:

**Comment by programistawpf** [comment]
Felipe, will you do it?
Paul

W dniu 2018-08-12 o 22:03, Felipe Noronha pisze:
