### ISSUE TITLE
Accept matrix as input for writetable!

### ISSUE THREAD

**Issue by felixrehren** [felipenoris/XLSX.jl#65]
Hello,

currently, there is some functionality for writing an `AbstractVector` ([see source](https://github.com/felipenoris/XLSX.jl/blob/a85d44e74ca62906ab49119d63bd5bc247bde327/src/write.jl#L315)). By default, a vector is written into a single row.

How about extending the interface to enable the following ? I could make a pull request, but would such an extension be desirable?

1. enable writing vectors into columns (same interface as writing into rows)
1. enable writing 2-D arrays, i.e. `AbstractMatrix` directly to the sheet (similar interface)

This could lead to some design changes:
* The functions available for `data::AbstractVector` where the row is an `Integer` and the argument for the columns is a `UnitRange` or a `Colon` could be duplicated with equivalent functions where instead the column is an `Integer` and the argument for the rows can be a `UnitRange` or a `Colon`
* The functions available for `data::AbstractVector` could be duplicated, but allowing `data::AbstractMatrix` and corresponding possibilities for the row/column arguments
* `Base.setindex!(sheet::Worksheet, data::AbstractVector, ref_str::AbstractString)` currently converts `ref_str` to a `CellRef`. Instead, one could try to convert it to either a `CellRef` or to a `CellRange` and then proceed accordingly

**Comment by felipenoris** [comment]
@felixrehren, the idea of a spreadsheet is to have a set of labeled columns. But there is also the kind of user case for matrices, like correlation matrices. So your proposal is welcome. Go ahead if you want to make a PR. Just try to make it non-beaking.

**Comment by felipenoris** [comment]
Done in 8d95b42.
