### ISSUE TITLE
00:00:00 to 1899-12-30 bug with XLSX

### ISSUE THREAD

**Issue by GregFa** [felipenoris/XLSX.jl#68]
In my data set, I have a data type Time in 24-hour notation where midnight is written as 00:00:00. Then if I read the data with ```XLSX.readdata()```, then 00:00:00 is converted to the date 1899-12-30. This is with julia v0.7 and XLSX v0.4.2

For example, let's say that we have an excel file (test.xlsx) with only one column such that:
| Time       |
|-------------|
| 23:58:00 |
| 23:59:00 |
| 00:00:00 |
| 00:01:00 |

If I extract the time from the excel files using ```XLSX.readdata()```, I get the following :

```
julia> x = XLSX.readdata("test.xlsx", "Sheet1", "A2:A5") 

4×1 Array{String,2}:
 "23:58:00"  
 "23:59:00"  
 "1899-12-30"
 "00:01:00"
```

I know that this bug is common with spreadsheets software data manipulations. Is there a fix to that bug? (Besides writing a function to filter the date.)

Thank you in advance.

**Comment by felipenoris** [comment]
@GregFa, thanks for reporting this bug. It should now be fixed. Sorry about the delay.
