### ISSUE TITLE
Excel file with charts can't be opened

### ISSUE THREAD

**Issue by pbouffard** [felipenoris/XLSX.jl#70]
When using `readxlsx` I get `ERROR: Couldn't parse worksheet somefile.xlsx`. A copy of the file with the tabs containing charts removed is read successfully.

**Comment by felipenoris** [comment]
@pbouffard Thanks for reporting this issue! I can't reproduce this error. Can you provide a file that reproduces this error?

**Comment by felipenoris** [comment]
Please, reopen this if the problem persists.
