### ISSUE TITLE
error on openxlsx with PrinterSetting

### ISSUE THREAD

**Issue by yongheekim-dev** [felipenoris/XLSX.jl#71]
I was trying to add new sheet to my working file, and encountered error 

https://drive.google.com/file/d/1j3Ajooj6j8LmrEd7wrc8ylDK7Y5YldZy/view?usp=sharing
``` julia
p = joinpath(@__DIR__, "temp.xlsx")
XLSX.openxlsx(p, mode="rw") do xf
    sheet = xf[1]
    @show xf
end
```
`ERROR: MethodError: no method matching read(::ZipFile.ReadableFile, ::Type{UInt8}, ::UInt32)`

it happens on here while trying to read `xl/printerSettings/printerSettings1.bin`
https://github.com/felipenoris/XLSX.jl/blob/master/src/read.jl#L181

`ZipFile.read(f, UInt8, f.uncompressedsize)` ->`ZipFile.read(f)` seems to work. But I don't know it's right thing to do

**Comment by felipenoris** [comment]
Hi @yongheekim-dev ! Thanks for reporting this!

It should be hitting this line of code for binary files, in read.jl -> open_or_read_xlsx:
```julia
# Binary file
# we only read binary files to save the Excel file later
xf.binary_data[f.name] = ZipFile.read(f, UInt8, f.uncompressedsize)
```

I just asked for permission to download your file to test it.

**Comment by felipenoris** [comment]
I'm hitting another error, already identified at #62 .

```julia
julia> XLSX.openxlsx(p, mode="rw") do xf
          sheet = xf[1]
          @show xf
       end
ERROR: AssertionError: Couldn't find xl//xl/worksheets/sheet1.xml in test.xlsx.
Stacktrace:
 [1] open_internal_file_stream at /home/felipenoris/.julia/dev/XLSX/src/stream.jl:48 [inlined]
 [2] read_worksheet_dimension(::XLSX.XLSXFile, ::String, ::String) at /home/felipenoris/.julia/dev/XLSX/src/worksheet.jl:15
 [3] XLSX.Worksheet(::XLSX.XLSXFile, ::EzXML.Node) at /home/felipenoris/.julia/dev/XLSX/src/worksheet.jl:7
 [4] parse_workbook!(::XLSX.XLSXFile) at /home/felipenoris/.julia/dev/XLSX/src/read.jl:317
 [5] open_or_read_xlsx(::String, ::Bool, ::Bool, ::Bool) at /home/felipenoris/.julia/dev/XLSX/src/read.jl:191
 [6] #openxlsx#14(::String, ::Bool, ::Function, ::getfield(Main, Symbol("##3#4")), ::String) at /home/felipenoris/.julia/dev/XLSX/src/read.jl:119
 [7] (::getfield(XLSX, Symbol("#kw##openxlsx")))(::NamedTuple{(:mode,),Tuple{String}}, ::typeof(XLSX.openxlsx), ::Function, ::String) at ./none:0
 [8] top-level scope at none:0
```

**Comment by YongHee-Kim** [comment]
That error don't happens to me. 
Excel file is created with Office 2019(Korean) & Windows 10 (Korean)

Maybe it's something to do with [EUC-KR](https://en.wikipedia.org/wiki/Extended_Unix_Code#EUC-KR) encoding? it's known to cause headaches when reading office document from windows with different locale.

**Comment by YongHee-Kim** [comment]
I've added printerSettings on one of your example data. (Just opend it from Office on my machine, and saved it again)
https://drive.google.com/file/d/1p9Xnz5AQKN6pUYz0CMSaLgfefp2zJPf-/view?usp=sharing

Does this work?

**Comment by felipenoris** [comment]
Maybe the files are being read in different order. Either way I'll have to work on #62 along with this issue.

**Comment by felipenoris** [comment]
@YongHee-Kim, looks like there was a change in ZipFile API, and your suggestion just fixes the problem. Thanks!!

I pushed the changes to branch `dev`. Would you mind testing from that branch and check if the problem is solved for you?

Cheers!

**Comment by yongheekim-dev** [comment]
it works great! I've added test for window generate xlsx file. 

Thank you 😄

**Comment by felipenoris** [comment]
Nice! Thank you!
