### ISSUE TITLE
How to insert vector  verticaly to existing file ?

### ISSUE THREAD

**Issue by programistawpf** [felipenoris/XLSX.jl#82]
Hi,
XLSX is very usuefull, thanks! 
Below, my new vector rand(5) is starting from cel B2, but in sheet is horizontaly. How to insert vector  but verticaly ? In cels  B1:B10  ? 

> julia> XLSX.openxlsx("my_new_file.xlsx", mode="rw") do xf
>            sheet = xf[1]
>                sheet["B2"] = rand(5)
>                end
> 5-element Array{Float64,1}:
>  0.19797082062820803
>  0.48317579235510166
>  0.09707096411823213
>  0.26370710993348934
>  0.8109768288800014
> 
Thanks
Paul

**Comment by felipenoris** [comment]
You could do it setting one cell at a time, but I'm adding a helper function for this at #83.

**Comment by felipenoris** [comment]
Done in 20f1c40.
Check latest docs. There will be a new release in a few days.

**Comment by programistawpf** [comment]
Thanks, is usefull. 
Is posible to add new sheet to existing file ?
Paul

**Comment by felipenoris** [comment]
@programistawpf yes, use `XLSX.addsheet!(wb, "name")`  on a writable workbook.

**Comment by programistawpf** [comment]
Is it posible it without loop

> XLSX.openxlsx("my_new_file.xlsx", mode="rw") do xf
> somthing
> end
How I can do xf writable after the loop ?
?

**Comment by felipenoris** [comment]
If you mean *without the [do-block-syntax](https://docs.julialang.org/en/v1/manual/functions/index.html#Do-Block-Syntax-for-Function-Arguments-1)*, not currently. But you could take a look at the implementation of `openxlsx` and create your own version.

I'll open an issue to implement this.
