### ISSUE TITLE
`addsheet!` automatically selects new sheet by default

### ISSUE THREAD

**Issue by fishix10** [felipenoris/XLSX.jl#86]
Files generated by the library with multiple sheets have all the sheets selected.

Looking at the xml file, I found that sheets generated by `addsheet!` automatically specify `tabSelected="1"` in `sheet#.xml` file.

**Comment by felipenoris** [comment]
Thanks for noticing this!

**Comment by felipenoris** [comment]
This was fixed by ce20d8d.
