### ISSUE TITLE
TableRows are truncated if column is blank

### ISSUE THREAD

**Issue by bjarthur** [felipenoris/XLSX.jl#89]
if there is a blank column in an excel sheet, it shows up as missing in the `XLSXFile`, which is good, but every column thereafter is inaccessible with `TableRow`.

```
julia> mydata = XLSX.readxlsx("mydata.xlsx")
XLSXFile("mydata.xlsx") containing 1 Worksheets
            sheetname size          range        
-------------------------------------------------
             data_all 820x49        A1:AW820     


julia> dropdims(mydata["data_all"]["A2:Z2"],dims=1)
26-element Array{Any,1}:
    "10.1"    
 490          
    "20101213"
    "20130311"
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
    missing   
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
    missing   
   1.0        
   1.0        

julia> row = first(XLSX.eachtablerow(mydata["data_all"]))
XLSX.TableRow(1, XLSX.Index(Dict(Symbol("5FP")=>8,Symbol("1FP")=>5,Symbol("Last Assay Date")=>4,Symbol("# Replicates")=>2,Symbol("First Assay Date")=>3,Symbol("40FP")=>11,Symbol("3FP")=>7,Symbol("80FP")=>12,Symbol("20FP")=>10,Symbol("2FP")=>6…), Symbol[:Construct, Symbol("# Replicates"), Symbol("First Assay Date"), Symbol("Last Assay Date"), Symbol("1FP"), Symbol("2FP"), Symbol("3FP"), Symbol("5FP"), Symbol("10FP"), Symbol("20FP"), Symbol("40FP"), Symbol("80FP"), Symbol("160FP")], Dict(2=>2,11=>11,7=>7,9=>9,10=>10,8=>8,6=>6,4=>4,3=>3,5=>5…)), Union{Missing, Bool, Float64, Int64, Date, DateTime, Time, String}["10.1", 490, "20101213", "20130311", 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0])

julia> row[15]
ERROR: BoundsError: attempt to access 13-element Array{Union{Missing, Bool, Float64, Int64, Date, DateTime, Time, String},1} at index [15]
Stacktrace:
 [1] getindex at ./array.jl:729 [inlined]
 [2] getdata at /groups/scicompsoft/home/arthurb/.julia/packages/XLSX/p413x/src/table.jl:262 [inlined]
 [3] getindex(::XLSX.TableRow, ::Int64) at /groups/scicompsoft/home/arthurb/.julia/packages/XLSX/p413x/src/table.jl:247
 [4] top-level scope at none:0

julia> row.cell_values
13-element Array{Union{Missing, Bool, Float64, Int64, Date, DateTime, Time, String},1}:
    "10.1"    
 490          
    "20101213"
    "20130311"
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
   1.0        
```

**Comment by felipenoris** [comment]
Hi!

Looks like this is the intended behavior. Please check [gettable docs](https://felipenoris.github.io/XLSX.jl/stable/api/#API-Reference-1): If columns is not given, the algorithm will find the first sequence of consecutive non-empty cells.

If this does not explain your issue, I could take a look if you provide an excel file example demonstrating the issue.

**Comment by bjarthur** [comment]
that's not very intuitive to me.  what's wrong with returning *all* columns except *trailing* non-empty cells?

thanks for the great package btw.  nice to have a native-julia excel reader!

**Comment by felipenoris** [comment]
People often organize Excel spreadsheets with many tables in a single worksheet *side-by-side*.
Defining a table as having a list of *non-empty consecutive columns* fits well for this kind of usage.

If your case does not fit in this default, you have to supply the table range manually, by identifying the set of columns that defines your table.

**Comment by fbruetting** [comment]
Thanks @felipenoris for explaning the reason! But oftentimes `A1` is empty because `A2:Axyz` contain the row headers and `B1:xyz` contain the column headers. The current behaviour then just starts reading at column `B` and ignores the whole `A` column. It’s pretty cumbersome to find out the boundaries for variying tables. What about an optionnal switch for the behaviour asked here, like `read_full_table=true/false`? That would make everybody happy. 😊️
