### ISSUE TITLE
KeyError on readxlsx of Read-Only File

### ISSUE THREAD

**Issue by jkort** [felipenoris/XLSX.jl#99]
Hello,
When trying to XLSX.readxlsx() a read-only file, I get this error:

`julia> xf = XLSX.readxlsx(filnam)
ERROR: KeyError: key "r" not found
Stacktrace:
 [1] getindex at C:\Users\jort\.julia\packages\EzXML\r19gO\src\streamreader.jl:4
62 [inlined]
 [2] iterate(::XLSX.SheetRowStreamIterator, ::Nothing) at C:\Users\jort\.julia\p
ackages\XLSX\2GLh4\src\stream.jl:131
 [3] iterate(::XLSX.WorksheetCache{XLSX.SheetRowStreamIterator}, ::Int64) at C:\
Users\jort\.julia\packages\XLSX\2GLh4\src\stream.jl:238
 [4] iterate(::XLSX.WorksheetCache{XLSX.SheetRowStreamIterator}) at C:\Users\jor
t\.julia\packages\XLSX\2GLh4\src\stream.jl:222
 [5] open_or_read_xlsx(::SubString{String}, ::Bool, ::Bool, ::Bool) at C:\Users\
jort\.julia\packages\XLSX\2GLh4\src\read.jl:229
 [6] readxlsx(::SubString{String}) at C:\Users\jort\.julia\packages\XLSX\2GLh4\s
rc\read.jl:37
 [7] top-level scope at none:0`

  If I "Save As" the original file into a new copy that is NOT read-only, it works.  Since I will repeatedly get access to read-only files that I cannot alter, only do the Save As, I 'd prefer to avoid the extra step.  Is there anyway to tell XLSX.jl I only want to open the file for read access?

Many thanks for your package, and for your help!

**Comment by felipenoris** [comment]
This looks like a Windows issue.

**Comment by jkort** [comment]
Thank you Felipe, for looking into this so quickly!

In my haste, I neglected to mention that I am working under Windows Server 2012 R2, Julia 1.0.3, XLSX 0.5.2.

Are you saying this is a Windows-specific issue for XLSX that you might be able to address, OR a problem inherent to Windows that I need to just accept?

Thanks again!
-Jack

**Comment by felipenoris** [comment]
Oh, it was just a remainder for myself that I couldn't reproduce the bug on Linux or macOS.

How do you mark a file as read-only?

**Comment by jkort** [comment]
In Windows, you right-click a file in the Windows Explorer file viewer, and there is a "read-only" attribute that can be checked/unchecked.  Open the file in Excel 2016 in Windows, and it will notify you that the file cannot be modified.

These are files controlled by another user, and I cannot (well, should not) change that attribute.

Anything else I can do in Windows to help you, do not hesitate to ask.

**Comment by felipenoris** [comment]
I really can't reproduce this. Tried on Windows 10.
Try again on the latest version of XLSX. Reopen the issue if the problem persists.
